Fixed yml

diff --git a/.github/workflows/27105_test.yml b/.github/workflows/27105_test.yml
--- a/.github/workflows/27105_test.yml
+++ b/.github/workflows/27105_test.yml
@@ -23,15 +23,25 @@ jobs:
         
       - name: Check files
         run: |
-           if [ ! -d ".errors" ]; then
-            mkdir -p .errors
-           fi
-           if [ ! -d "tests" ] || [ -z "$(ls -A tests)" ]; then
+            if [ ! -d ".errors" ]; then
+              mkdir -p .errors
+            fi
+            if [ ! -d "tests" ] || [ -z "$(ls -A tests)" ]; then
               # Redirect error message to a file within the ".errors" folder
               echo "Error: Tests not found" > .errors/test_errors.txt
               exit 1
-           fi
-           
+            fi
+            if ! ls tests/*.py >/dev/null 2>&1; then
+              # Redirect error message to a file within the ".errors" folder
+              echo "Error: No Python files found in tests folder" > .errors/test_errors.txt
+              exit 1
+            fi
+      - name: Check functions test
+        run: |
+             if [ ! -f "tests/functions_test.py" ]; then
+               echo "Error: functions_test.py does not exist" > .errors/test_errors.txt
+               exit 1
+             fi
   testing:
     runs-on: 
       - self-hosted
@@ -50,10 +60,10 @@ jobs:
       - name: Get pip with python
         run: "python -m ensurepip --upgrade --user"
 
-      - name: Installations
+      - name: Other installations
         run: |
           pip install pytest>=8.1.1
           pip install numpy>=1.26.4
   
-      - name: Run test
+      - name: Run tests
         run: pytest
