updated

diff --git a/.github/workflows/27105_test.yml b/.github/workflows/27105_test.yml
--- a/.github/workflows/27105_test.yml
+++ b/.github/workflows/27105_test.yml
@@ -11,7 +11,7 @@ jobs:
       - self-hosted
     strategy:
       matrix:
-        pip-version: [latest,24.0]
+        pip-version: [ latest,24.0 ]
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
@@ -46,17 +46,6 @@ jobs:
     needs: check_tests
     if: ${{ needs.check_tests.result == 'success' }}
     steps:
-      - name: Get artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: napake
-
-      - name: Check artifact errors
-        run: |
-          if grep -q "error" .errors/napake.txt; then
-            exit 1
-          fi
-
       - name: Setup
         uses: actions/setup-python@v5
         with:
@@ -70,6 +59,17 @@ jobs:
       - name: Other installations
         run: |
           pip install -r req.txt
+
+      - name: Get artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: napake
+
+      - name: Check artifact errors
+        run: |
+          if grep -q "error" .errors/napake.txt; then
+            exit 1
+          fi
 
       - name: Run tests
         run: pytest
